csduarte/platform

webapp/components/post_view/components/post_list.jsx
CD Fix Conflict for next merge to shift
=> Fix Conflict for next Merge to shift

api/channel_test.go, model/version.go, store/sql_upgrade.go
=> Cd 110716 merge

config/config.json, model/config.go, utils/config.go, webapp/components/login/login_controller.jsx
Added CustomOverride to handle these one off cases. @csduarte
=> TSDEV-76 Make sure that correct login placeholder is displayed

webapp/sass/routes/_about-modal.scss
=> TSDEV-111 fix gray uchat icon in about modal

webapp/components/admin_console/admin_sidebar_header.jsx, webapp/components/sidebar_header.jsx, webapp/sass/layout/_headers.scss, webapp/sass/layout/_sidebar-menu.scss, webapp/sass/responsive/_mobile.scss
Tested locally with different resolutions:
Tested locally with long name:
=> [TSDEV-51] display user fullname instead of team name on top-left

webapp/components/profile_picture.jsx
Ran `npm run check`
```
egui-C02SF1D9G8WM:webapp egui$ npm run check
> mattermost-webapp@0.0.1 check /Users/egui/gocode/src/github.com/mattermost/platform/webapp
> eslint --ext ".jsx" --ignore-pattern node_modules --quiet .
```
=> fix lint errors in profile_picture.jsx

webapp/components/user_settings/user_settings_advanced.jsx, webapp/components/user_settings/user_settings_general.jsx
UCHAT-29 Hide pre-release features section of advanced settings pane
UCHAT-34 Hide nickname option in settings panel
=> UCHAT-29 UCHAT-34 Hide pre-release features & nickname option in user settings modal

webapp/components/user_settings/user_settings_advanced.jsx, webapp/components/user_settings/user_settings_general.jsx, webapp/sass/layout/_post.scss
merge with release-3.5 && shift, only 1 conflict, eslint styles to change
=> Merge 11/18/16

api/user.go, i18n/en.json, templates/welcome_body.html
=> UCHAT-131 Whitelabel welcome email template

api/post.go, webapp/components/code_preview.jsx
Unfortunately, the 3.5.1 release was mostly covered already :(
=> Merge 112816

webapp/components/more_channels.jsx
=> UCHAT-142 fix exception from closing more channels modal

webapp/components/tutorial/tutorial_intro_screens.jsx
=> UCHAT-143 Remove tutorial reference to searching + archiving

webapp/components/searchable_user_list.jsx, webapp/i18n/en.json
=> UCHAT-189 Full-width search input in SearchableUserList

webapp/components/more_channels.jsx
fix lint error from my earlier commit
=> UCHAT-142 fix npm lint error

hooks/pre-commit, init.sh
- Added `hooks/` directly containing a `pre-commit` file that simply executes `make check-style`
- Added `init.sh` to change `core.hooksPath` to `hooks/` (the developer needs to run this init.sh when first checking out the repo)
- To skip pre-commit, check-in using `git commit --no-verify`
Sample successful commit:
```
egui-C02SF1D9G8WM:platform egui$ git commit -m 'test hook'
Checking client style
cd ./webapp && /Applications/Xcode.app/Contents/Developer/usr/bin/make check-style
Checking for style guide compliance
npm run check
> mattermost-webapp@0.0.1 check /Users/egui/gocode/src/github.com/mattermost/platform/webapp
> eslint --ext ".jsx" --ignore-pattern node_modules --quiet .
Running GOFMT
gofmt sucess
[master 480146c] test hook
1 file changed, 3 insertions(+)
create mode 100755 …
```
=> UCHAT-148 add pre-commit hook

webapp/components/navbar.jsx
Fix JS error described in: https://jira.uberinternal.com/browse/UCHAT-296
=> UCHAT-296 fix JS error when clicking add new members btn on mobile

model/config.go, webapp/sass/responsive/_mobile.scss
=> Merge 120916

webapp/components/login/login_controller.jsx
This fix is a bit of a guess. We're getting an undefined window object. But it's hard to check since saml is not configured, nor do we have an easy way of testing enterprise issues. I also submitted to platform to get some comments, because this fix seems likely.
We will need to test in staging along with the other hot fixes.
=> fix SAML bug

webapp/components/tutorial/tutorial_tip.jsx, webapp/i18n/en.json, webapp/i18n/es.json, webapp/i18n/fr.json, webapp/i18n/pt-BR.json
Ticket: https://jira.uberinternal.com/browse/UCHAT-201
=> UCHAT-201 Remove references to invites from coach tip on topbar dropdown menu

api/user.go, api/user_test.go, model/client.go, store/sql_user_store.go, store/sql_user_store_test.go, store/store.go
- Create endpoint `POST /teams/:team_id/users/usernames` to retrieve User with usernames
- Used existing `GetProfilesByUsernames` function to perform the selection
- Created unit test
URL: `POST http://localhost:8065/api/v3/teams/19dzimg4pinmzrccughy46hjqo/users/usernames`
Body: `["test4", "egui"]`
Response:
```
{
"egui": {
"id": "3pkog3y58jbxtnc6r1hw71xtbh",
"create_at": 1481829286748,
"update_at": 1481829293359,
"delete_at": 0,
"username": "egui",
"auth_data": "",
"auth_service": "",
"email": "egui@uber.com",
"nickname": "",
"first_name": "",
"last_name": "",
"roles": "system_admin system_user",
"locale": "en"
},
"test4": {
"id": "18g4i9bmnty7zqub4eps77fpwe",
"create_at": 1481848461283,
"update_at": 1481848461418,
"delete_at": 0,
"username": "test4",
"auth_data": "",
"auth_service": "", …
```
=> UCHAT-460 add endpoints to retrieve user with username or email

store/sql_user_store_test.go
Fixed the map lookup to search by correct key (Email, not Id)
the change of the import was unavoidable thanks to gofmt.
=> Fix test failure for email lookup
