csduarte/platform

- webapp/components/user_settings/user_settings_display.jsx
This PR currently hides theme, font and display name for display settings.
> Add mocked configs for display settings

- config/config.json
- model/config.go
- utils/config.go
- webapp/components/admin_console/users_and_teams_settings.jsx
- webapp/components/login/login_controller.jsx
- webapp/components/more_direct_channels.jsx
- webapp/components/root.jsx
- webapp/components/sidebar_header_dropdown.jsx
This PR allows an admin user to manage a default team through the admin console.  When doing so, users will skip the choose a team selection page and be redirected to the default team chat page.
> Allow default team to be configured

- webapp/components/login/login_controller.jsx
- webapp/sass/layout/_footer.scss
- webapp/sass/responsive/_mobile.scss
- webapp/sass/routes/_signup.scss
- Hide footer on mobile. @csduarte Should we hide the footer on all screen sizes?
- Hide "Create New Account" text/button on all screen sizes
- Hide "I forgot my password" link on all screen sizes
- Add new `.btn--link` class makes links behave like buttons while retaining the default link aesthetic (currently scoped exclusively to `.signup-team__container`).
- Set minimum button width scoped to signup__container (currently scoped exclusively to `.signup-team__container`)
- Right-align sign in button for better usability for the majority of users.
> Redesign mobile login

- webapp/sass/components/_modal.scss
Fixes the aesthetic of `.modal-header .btn-primary` set by the `theme.sidebarHeaderBg` variable, adding a small white stroke.
I checked every instance of `.modal-header` in use and the use of the theme variable. This change should be safe for future additions to mattermost/master.
> Set custom style for instances of `.modal-header .btn-primary`

- webapp/components/profile_picture.jsx
- webapp/sass/components/_modal.scss
- webapp/sass/components/_popover.scss
- webapp/sass/layout/_headers.scss
- webapp/sass/layout/_post.scss
Use `object-fit: cover;` in various places to allow scaling while preserving aspect ratio on profile pictures
Before:
After:
> TSDEV-143 fix aspect ratio issue with rectangular profile images

- webapp/components/textbox.jsx
- webapp/sass/layout/_post.scss
Currently, in Mattermost and our version, there's a dangling "Help" link if the user types more than one line of text in the input box:
This PR removes the "Help" link which seems to be from a disabled feature.
> UCHAT-122 remove the dangling help link near text input

- webapp/components/create_post.jsx
- webapp/sass/layout/_post.scss
- webapp/sass/responsive/_tablet.scss
After some further investigation, the dangling help link is caused by the `help__text` being inside the `textbox.jsx` component instead of `post-create-footer`, so when the responsive layout is being applied, the help link does not get hidden.
This commit moves the `help__text` div into the proper container and hide it in mobile and tablet layout.
Desktop layout:
Tablet/Mobile layout:
> UCHAT-122 hide help link properly for tablet sized screens

- model/user.go
- webapp/components/post_view/components/post_list.jsx
- webapp/components/user_settings/user_settings_notifications.jsx
For new users, the function `SetDefaultNotifications` is called. However, some of the default values are currently being set in the webapp itself. This PR changes some of the default notification values, and set the missing fields from the server.
Note: I verified from them webapp UI that the new defaults are being displayed, but I have not completed a thorough test on whether if these notifications settings are indeed working.
> UCHAT-60 change default notification settings for new users

- webapp/components/get_android_app/get_android_app.jsx
Changed text from 'Download' to 'Use' to better reflect the case new case that if the user has the app installed it will open the uChat Android app.
IMPORTANT: on the go configuration the value of `AndroidAppDownloadLink` needs to be set to `https://prod.com/downloads`
> UCHAT-78 Configure app url scheme/intent for android app

- webapp/components/navbar.jsx
This PR adds an onClick listener to Popover, so the modal gets closed when the user clicks on it on mobile. The drawback to this approach is the modal gets closed when the user touches anywhere on it. 
The reason why the default modal's "root close" behavior does not seem to work is because of the way this mobile CSS styling is being overridden. Popover component in `react-bootstrap` just looks like a tooltip, so when the user clicks anywhere "outside", the hide code is triggered. However, here it's being stretched into a fullscreen overlay, so there's nowhere that's considered "outside", so the closing code is never being triggered (unless the user clicks on the nav bar).
> UCHAT-13 close modal when clicking background

- api/channel.go
This should fix the permissions error that was intermittently encountered when creating a new DM/channel.
https://github.com/mattermost/platform/pull/4694
https://mattermost.atlassian.net/browse/PLT-4750
> UCHAT-36 Invalidate user channel members cache when creating a new channel

- webapp/sass/layout/_headers.scss
When the user does not have a first name nor last name, then header menu would appear misaligned as such:
This should only happen during dev, as we expect our users to have a proper first name and last name.
This PR addresses this misalignment issue by using flexboxes to justify the contents in the green header to center, and set a min-height for the header.
Results:
> UCHAT-186 set a min-height for the sidebar menu header

- webapp/sass/layout/_post.scss
There's some oddities with the reply menu currently if the user hovers over a one line message:
This PR addresses the issue by toggling between `display: none;` and `display: inline-block;` for that particular menu.
Demo:
> UCHAT-169 fix hover issue with reply menu for one line messages

- webapp/components/channel_invite_modal.jsx
- webapp/components/searchable_user_list.jsx
- Add missing property in `channel_invite_modal` component to focus search input upon creation
- Fix async timing issue causing focus to not be set when transitioning from "View Members" to "Add New Members to <channel-name>" using the "Add New Members" button. 
Before Demo:
After Demo:
> UCHAT-73 focus search input when Add members modal gets displayed

- webapp/components/channel_invite_modal.jsx
- webapp/components/more_channels_new.jsx
- webapp/components/more_direct_channels.jsx
- webapp/components/team_members_modal.jsx
- webapp/sass/responsive/_mobile.scss
Ticket: https://jira.uberinternal.com/browse/UCHAT-285
These changes touch the height so that the scroll works properly. All members and channels modals should be tested:
- From the current channel menu: Add Members, View Members, Manage Members
- View Members (From the 3 dots drop down menu)
- More... (Channels)
- More... (Direct Message)
Added specific styles for special cases like in 'config/config.json' setting any of these values:
"RestrictPublicChannelManagement": "all",
"RestrictPrivateChannelManagement": "all",
"DefaultTeamName": ""
> UCHAT-285 DM modal has messed up layout on mobile

- store/sql_channel_store.go
These changes fix:
UCHAT-282 - Channels pagination api doesn't filter by team
UCHAT-288 - Channel search is not respecting private rooms in modal
UCHAT-289 - In Channels modal, hide already joined channels
Tickets:
https://jira.uberinternal.com/browse/UCHAT-282
https://jira.uberinternal.com/browse/UCHAT-288
https://jira.uberinternal.com/browse/UCHAT-289
> UCHAT-282 Enclose OR so that the query executes with the proper parameters

- webapp/components/channel_switch_modal.jsx
- webapp/components/suggestion/suggestion_box.jsx
- Add optional property `overrideEnterKey` to `SuggestionBox` component to allow overriding default enter key handling (default autocompletes)
- Use `overrideEnterKey` in `SwitchChannelModal` component to allow switching channels using enter key directly on the suggestions list
Demo gif:
> UCHAT-227 allow single enter key to switch channels in channel switcher

- api/channel.go
- webapp/components/channel_invite_modal.jsx
- webapp/components/channel_members_modal.jsx
- webapp/components/more_channels_list.jsx
- webapp/components/more_channels_new.jsx
- webapp/components/more_direct_channels.jsx
- webapp/components/searchable_user_list.jsx
- webapp/components/team_members_modal.jsx
- webapp/i18n/en.json
- webapp/i18n/es.json
- webapp/i18n/fr.json
- webapp/sass/components/_modal.scss
- webapp/sass/responsive/_mobile.scss
Ticket: https://jira.uberinternal.com/browse/UCHAT-202
- Changed it to 'Load more' button centered with spinner on click.
- Added channel count to be able to know when to hide load more button.
- Logic added to Channels modal, Direct Message modal, View Members, Add Members.
- Removed bottom 'Close' buttons in modals 
- Display message when 'No Channels Found' when searching
--------------------------
Move "Next" button in channel lists
In channel lists, e.g. Manage/View Members modal and "More..." list in direct message channels, move "Next" button to the bottom of the user list
P2: On mobile, show a scrollbar when the list appears, not only once you start scrolling (this already happens on the browser)
NOTE:
This was work previously done for MM but never merged: …
> UCHAT-202 Move next button to bottom of results list in paginated modals

- webapp/root.html
Currently if network error (disconnect) occurs prior to all the javascript finishes loading, the user is presented with a blank page. This is because the `window.setup_root` function has not been set. This PR adds the following message to the screen when `window.setup_root` is `undefined`.
I've tested this on 
See [this video demo](https://drive.google.com/a/uber.com/file/d/0B33KDfvd_OtVNHJ3enBpMUNEMzg/view?usp=sharing) for iOS. 
❗️ Note: the loading takes a while because I was connecting through ngrok to my laptop from my iPhone .
Two related text changes:
https://github.com/csduarte/uchat-android/pull/14
https://github.com/csduarte/uchat-ios/pull/19
> UCHAT-232 add error message to root.html that is displayed during network error

- api/user.go
When the server cannot read from S3 it creates a temporary image and *somehow* saves it back to s3, this effectively overwrites the user's profile image.
This hotfix will prevent the writing of the default image if the profile picture has ever been modified. The default image will serve an image cached for 300 seconds.
> uChat hotfix for profile wipe

- webapp/components/sidebar_right_menu.jsx
Ticket: https://jira.uberinternal.com/browse/UCHAT-306
NOTE: It related to this previous PR: https://github.com/csduarte/platform/pull/3/files
Result when `DefaultTeamName` is set to an existing team:
> UCHAT-306 Team selection link is displayed in RHS on mobile

- api/status.go
- api/status_test.go
- model/client.go
- webapp/client/client.jsx
- webapp/components/admin_console/admin_sidebar_header.jsx
- webapp/components/sidebar.jsx
- webapp/components/sidebar_header.jsx
- webapp/components/sidebar_header_status_dropdown.jsx
- webapp/images/icons/IC_DM_Away.svg
- webapp/images/icons/IC_DM_Offline.svg
- webapp/images/icons/IC_DM_Online.svg
- webapp/sass/layout/_headers.scss
- webapp/sass/responsive/_mobile.scss
- webapp/tests/client_user.test.jsx
- webapp/utils/utils.jsx
- Add a status dropdown to allow user to manually set status
- Add an endpoint to set status 
- `POST /users/status`
- POST body is a JSON string denoting the status (e.g. "online", "offline", and "away")
- Add basic client and server unit test for set status endpoint (test passes locally)
- Modify sidebar header to conform with latest designs
- Tested CSS styles on system console
- Tested CSS styles on mobile resolutions
- Tested on dark theme
- Tested users with varying lengths of names (for dev only, if the user does not have firstname and lastname, then the following is displayed:)
> UCHAT-150 add dropdown in sidebar header for changing status

- webapp/components/suggestion/switch_channel_provider.jsx
Display full names in our current channel switcher design:
Because the designs are not final, this is just a quick simple fix to get the full name to show as part of the suggestions.
> UCHAT-211 display fullname in channel switcher suggestions

- api/preference.go
- api/preference_test.go
- model/client.go
- Added `POST /preferences/admin/save` to allow system admin to set preference for a user with the given user_id
- Added unit test
- Tested on Postman:
`POST http://localhost:8065/api/v3/preferences/save`
response:
```
{
"id": "api.preference.save_preferences.set.app_error",
"message": "Unable to set preferences for other user",
"detailed_error": "session.user_id=3pkog3y58jbxtnc6r1hw71xtbh, preference.user_id=18g4i9bmnty7zqub4eps77fpwe",
"request_id": "pspn45gchbf6bj1w3x87pm4gec",
"status_code": 403
}
```
`POST http://localhost:8065/api/v3/preferences/admin/save`
response:
`true`
> UCHAT-448 add an API for admins to modify user preferences

- api/import.go
- api/webhook.go
- api/webhook_test.go
- i18n/en.json
- model/post.go
Ticket: https://jira.uberinternal.com/browse/UCHAT-465
Reference from MM: https://github.com/mattermost/platform/pull/4879
Issue: A fairly serious performance issues caused by a heavy user bot/service. Partial solution: Webhook errors should not return 500s, but 400s so that the bot will know not to retry
> UCHAT-465 - Return 400 bad request codes for webhooks when attachment or text is too long (#4879)

- config/config.json
- model/config.go
- utils/config.go
- utils/diagnostic.go
- webapp/components/admin_console/email_authentication_settings.jsx
- webapp/components/login/login_controller.jsx
- webapp/i18n/en.json
- webapp/sass/routes/_signup.scss
- Add two config options: `EmailSignInHidden` and `UsernameSignInHidden`
- Change styling when both email and username signin are hidden
- Add corresponding setting toggle in system console
- Briefly tested locally by manually overriding settings inside client code
> UCHAT-472 Add setting to hide email/username signin and adjust styling

- api/user.go
- config/config.json
- model/config.go
- utils/config.go
- utils/diagnostic.go
- webapp/components/admin_console/admin_team_members_dropdown.jsx
Created to config that would disable authentication transfer methods, ex: ldap to email/password. 
Screenshots of various postman outputs
methods remain enabled:
invalid token:
Email to ldap:
oauth to email:
email to oauth:
ldap to email:
> SSO Disable Transfer

- webapp/components/file_attachment.jsx
- webapp/images/download_CTA.svg
- webapp/sass/components/_files.scss
- webapp/sass/layout/_post.scss
- webapp/sass/responsive/_mobile.scss
Modify the file_attachment component to reflect new designs for image previews:
- tested on mobile and desktop resolutions
- ran precommit style checks
> UCHAT-151 modify the image attachment preview to match design

- webapp/components/profile_popover.jsx
If you click the profile popover in staging right now, you will see a javascript error because the overlay is undefined. Not sure if the overlay needs to be dismissed, so just put a if clause just in case.
> prevent calling hide on undefined

- webapp/components/channel_switch_modal.jsx
In the channel switcher, the "Switch" button does not work right now. This is because in one of my previous changes, I modified the signature of `handleSubmit` function to take in a `selectionText` argument. 
However, `handleSubmit` is also being used as an event handler for the "Switch" button. 
Consequently, the assignment: `const name = selectionText || this.state.text.trim();` would assign `name` as the `submit` event instead.
This PR addresses this issue by changing the `handleSubmit` function to include the previously omitted argument.
> UCHAT-516 fix switch button in channel switcher
